name: Production deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: 1
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ env.VERCEL_ORG_ID}}
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID}}
          scope: ${{ env.VERCEL_ORG_ID}}
          working-directory: ./
          vercel-args: '--prod'
          github-comment: false
